package window

import lua_common "../lua_common"

WINDOW_NAMESPACE :: lua_common.LuaNamespace {
	name      = "window",
	functions = []lua_common.LuaFunction {
		SET_MOUSE_LOCK_FUNCTION,
		GET_MOUSE_LOCK_FUNCTION,
		GET_MOUSE_VISIBLE_FUNCTION,
		SET_MOUSE_VISIBLE_FUNCTION,
		SET_WINDOW_TITLE_FUNCTION,
		GET_WINDOW_TITLE_FUNCTION,
		SET_WINDOW_SIZE_FUNCTION,
		GET_WINDOW_SIZE_FUNCTION,
		SET_FULLSCREEN_FUNCTION,
		GET_FULLSCREEN_FUNCTION,
		SET_VSYNC_FUNCTION,
		GET_VSYNC_FUNCTION,
		SET_MAX_FPS_FUNCTION,
		GET_MAX_FPS_FUNCTION,
		QUIT_FUNCTION,
		ON_EXIT_FUNCTION,
		ON_INIT_FUNCTION,
		SHOW_DEBUG_INFO_FUNCTION,
		SET_KEEP_ASPECT_FUNCTION,
		GET_KEEP_ASPECT_FUNCTION,
		SET_WINDOW_ICON_FUNCTION,
		GET_WINDOW_ICON_FUNCTION,
		SET_CURSOR_FUNCTION,
		GET_CURSOR_FUNCTION,
	},
}
