package graphic

import lua_common "../lua_common"

GRAPHIC_NAMESPACE :: lua_common.LuaNamespace {
	name      = "graphic",
	functions = []lua_common.LuaFunction {
		RECT_FUNCTION,
		TEXT_FUNCTION,
		SET_BACKGROUND_FUNCTION,
		LOAD_SHADER_FUNCTION,
		ADD_POST_PROCESSING_FUNCTION,
		SET_POST_PROCESSING_ARGS_FUNCTION,
		REMOVE_POST_PROCESSING_FUNCTION,
		PRELOAD_TEXTURE_FUNCTION,
		GET_HOT_TEXTURE_THRESHOLD_FUNCTION,
		SET_HOT_TEXTURE_THRESHOLD_FUNCTION,
	},
}
